# Generated by Django 5.0.2 on 2024-02-29 12:57

import django.core.validators
import django.db.models.deletion
import re
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Convener',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('clerk_id', models.CharField(max_length=256)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assign.module')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assign.module')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('clerk_id', models.CharField(max_length=256)),
                ('projects', models.ManyToManyField(to='assign.project')),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('marks', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('state', models.CharField(choices=[('PENDING', 'Pending'), ('SUBMITTED', 'Submitted'), ('MODERATIONPENDING', 'Moderationpending'), ('MODERATED', 'Moderated')], default='PENDING', max_length=20)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assign.project')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assign.student')),
            ],
        ),
        migrations.CreateModel(
            name='Academics',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('clerk_id', models.CharField(max_length=256)),
                ('students', models.ManyToManyField(to='assign.student')),
            ],
        ),
    ]
