# Generated by Django 5.0.2 on 2024-03-03 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Academics',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('clerk_id', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Convener',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('clerk_id', models.CharField(max_length=256)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assign.module')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assign.module')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('preferences', models.CharField(max_length=100)),
                ('clerk_id', models.CharField(max_length=256)),
                ('projects', models.ManyToManyField(to='assign.project')),
            ],
        ),
        migrations.CreateModel(
            name='IndividualMark',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mark', models.IntegerField()),
                ('academics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assign.academics')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assign.project')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assign.student')),
            ],
            options={
                'unique_together': {('project', 'student', 'academics')},
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('PENDING', 'Pending'), ('SUBMITTED', 'Submitted'), ('MODERATIONPENDING', 'Moderationpending'), ('MODERATED', 'Moderated')], default='PENDING', max_length=20)),
                ('marks', models.ManyToManyField(blank=True, to='assign.individualmark')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assign.project')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assign.student')),
            ],
        ),
        migrations.AddField(
            model_name='academics',
            name='students',
            field=models.ManyToManyField(blank=True, to='assign.student'),
        ),
    ]
