# Generated by Django 5.0.2 on 2024-02-28 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('state', models.CharField(choices=[('PENDING', 'Pending'), ('SUBMITTED', 'Submitted'), ('MODERATIONPENDING', 'Moderationpending'), ('MODERATED', 'Moderated')], default='PENDING', max_length=20)),
                ('total_marks', models.IntegerField()),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assign.module')),
            ],
        ),
        migrations.CreateModel(
            name='Convener',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assign.module')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('exams', models.ManyToManyField(to='assign.exam')),
            ],
        ),
        migrations.CreateModel(
            name='Academics',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('students', models.ManyToManyField(to='assign.student')),
            ],
        ),
    ]
