# Generated by Django 5.0.2 on 2024-02-29 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assign', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='date',
        ),
    ]
