# Generated by Django 5.0.2 on 2024-02-28 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assign', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='academics',
            name='clerk_id',
            field=models.CharField(default='user_2d03D8Zfc2WlepmNH6w2rNYCQ3h', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='convener',
            name='clerk_id',
            field=models.CharField(default='user_2d03D8Zfc2WlepmNH6w2rNYCQ3h', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='clerk_id',
            field=models.CharField(default='user_2d03D8Zfc2WlepmNH6w2rNYCQ3h', max_length=256),
            preserve_default=False,
        ),
    ]
