# Generated by Django 5.0.2 on 2024-03-01 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assign', '0003_remove_grade_marks_individualmark_grade_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='marks',
            field=models.ManyToManyField(blank=True, to='assign.individualmark'),
        ),
        migrations.AlterUniqueTogether(
            name='individualmark',
            unique_together={('project', 'student', 'academics')},
        ),
    ]
