# Generated by Django 5.0.2 on 2024-03-02 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assign', '0005_alter_academics_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='preferences',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
